kumuluzee:
  name: catalogue-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:3000
    http:
      port: 3000
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      pool:
        max-size: 1
