kumuluzee:
  name: catalogue-service
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      pool:
        max-size: 1
